version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    image: cpazinatto/nginx
    container_name: nginx
    networks:
      - server-network
    ports:
      - "8080:80"
    depends_on: 
      - app

  app:
    container_name: app
    restart: always
    build: 
      context: ./node
    image: cpazinatto/node
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    networks: 
      - server-network
    depends_on: 
      - db
    command: npm start

  db:
    build: 
      context: ./mysql
    image: cpazinatto/mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/database:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - server-network
    command: --innodb-use-native-aio=0
    

networks: 
  server-network:
    name: server-network
    driver: bridge